# Dataset sintético de classificação (scikit-learn)
name: synthetic_classif
n_samples: 6000
n_features: 32
n_informative: 16
n_redundant: 0
n_repeated: 0
n_classes: 4
class_sep: 1.0
random_state: ${..seed}
test_size: 0.2
val_size: 0.1
batch_size: 64
num_workers: 0  # Windows: 0 evita problemas